name: co2_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi
    - uvicorn
    - mlflow
    - dvc[s3]
    - boto3
    - tensorflow==2.16.1
    - pandas
    - numpy
    - scikit-learn
    - PyYAML
    - prometheus_client
    - requests
    - keras